name: "Magento 2 Coding Standard"
on:
  pull_request:
    branches:
      - main
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer:2.3, phpcs:3.6
    - run: composer install
    - run: vendor/bin/phpcs --ignore=*/vendor/* src
